spring:
  datasource:
    url: jdbc:h2:mem:simgraduate_db;MODE=PostgreSQL
  jpa:
    hibernate:
      ddl-auto: create-drop

external-services:
  cep:
    via-cep-url: https://viacep.com.br/ws/{cep}/json
  scheduler:
    allan: https://chatbot-c8049.firebaseio.com/Evento.json